# Generated by Django 3.2.5 on 2022-07-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0006_alter_userinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_tables',
        ),
    ]
